name: main pipeline
run-name: run triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v9
        with:
          version: "0.12.5"
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      - run: uvx ruff check
