name: main pipeline
run-name: run triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6.1.0
      - name: Setup python
        uses: actions/setup-python@v6.3.0
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          version: "0.12.5"
          enable-cache: true
      - name: Run code linter
        uses: astral-sh/ruff-action@v4.1.0
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run tests # TODO: add report to the job summary
        run: uv run pytest

