name: dev
run-name: run triggered by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6.1.0
      - name: Setup python
        uses: actions/setup-python@v6.3.0
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          version: "0.12.5"
          enable-cache: true
      - name: Run code linter
        uses: astral-sh/ruff-action@v4.1.0
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest --html=pytest_report.html --self-contained-html
      - name: Store pytest test results
        uses: actions/upload-artifact@v7.0.1
        with:
          name: pytest-results
          path: pytest_report.html
          archive: false
        if: ${{ always() }}
      - name: Caching venv
        uses: actions/cache@v6.1.0
        with:
          path: .venv
          key: venv
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.1.0
      - name: Build docker image
        run: docker build -f app.dockerfile -t mike239x/demo_app .
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: mike239x/demo_app
      - name: Push docker image
        run: |
          docker login -u mike239x -p ${{ secrets.DOCKER_PASSWORD }}
          docker image push mike239x/demo_app
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.1.0
      - name: Setup python
        uses: actions/setup-python@v6.3.0
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          version: "0.12.5"
          enable-cache: true
      - name: Caching venv
        uses: actions/cache@v6.1.0
        with:
          path: .venv
          key: venv
      - name: Deploy to FastAPI Cloud
        run: uv run fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
