name: production
run-name: release created by ${{ github.actor }}
on:
  release:
    types: [released]

jobs:

  get-confirmation:
    environment: production_confirm
    runs-on: ubuntu-latest

  deploy:
    needs: get-confirmation
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.1.0
      - name: Setup python
        uses: actions/setup-python@v6.3.0
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          version: "0.12.5"
          enable-cache: true
      - name: Caching venv
        uses: actions/cache@v6.1.0
        with:
          path: .venv
          key: venv
      - name: Deploy to FastAPI Cloud
        run: uv run fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}


# on the off-chance I show this file during the interview, here's a cool ascii art I found

#                           ?
#~~~~~~~~~~~~~~~~~~~~~~~~~~~|^"~~~~~~~~~~~~~~~~~~~~~~~~~o~~~~~~~~~~~
#       o                   |                  o      __o
#        o                  |                 o     |X__>
#      ___o                 |                __o
#    (X___>--             __|__            |X__>     o
#                        |     \                   __o
#                        |      \                |X__>
# _______________________|_______\________________
#<                                                \____________   _
# \                                                            \ (_)
#  \    O       O       O                                       >=)
#   \__________________________________________________________/ (_)
#                           ___
#                          / o \
#                     __   \   /   _
#                       \__/ | \__/ \
#                      \___//|\\___/\
#                       ___/ | \___
#                            |     \
#                           /
#------------------------------------------------
