name: staging
run-name: release created by ${{ github.actor }}
on:
  release:
    types: [released]
jobs:
  test-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6.1.0
      - name: Say hello
        run: echo hello
