name: staging
run-name: tagged by ${{ github.actor }}
on:
  push:
    tags:        
      - v**

jobs:

  test-other-python-versions:
    environment: staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6.1.0
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.0
        with:
          version: "0.12.5"
          enable-cache: false
          python-version: ${{ matrix.python-version }}
      - name: Setup UV some more
        run: |
          echo hi > .python-version
          rm uv.lock
          uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest --html=pytest_report_${{ matrix.python-version }}.html --self-contained-html
      - name: Store pytest test results
        uses: actions/upload-artifact@v7.0.1
        with:
          path: pytest_report_${{ matrix.python-version }}.html
          archive: false
        if: ${{ always() }}
      - name: Caching venv
        uses: actions/cache@v6.1.0
        with:
          path: .venv
          key: venv

  tag-docker-image:
    needs: test-other-python-versions
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v6.1.0
      - name: Build docker image
        run: docker build -f app.dockerfile -t mike239x/demo_app .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: mike239x/demo_app
          format: table
          exit-code: 0
          output: image_vulnerabilities.txt
      - name: Store Trivy results
        uses: actions/upload-artifact@v7.0.1
        with:
          path: image_vulnerabilities.txt
          archive: false
        if: ${{ always() }}
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: mike239x/demo_app
      - name: Push docker image
        run: |
          docker login -u mike239x -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag mike239x/demo_app mike239x/demo_app:${{ github.ref_name }}
          docker push mike239x/demo_app:${{ github.ref_name }}

  deploy:
    needs: tag-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.1.0
      - run: echo hi there
#      - name: Deploy to FastAPI Cloud
#        run: uv run fastapi deploy
#        env:
#          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
#          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
